---
deployment:
  tasks:
    - export DEPLOYPATH=/home/paylesot/public_html/pay-lesotho-website
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp final-style.css $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH